plugins {
    id 'com.gradleup.shadow' version '8.3.0' apply false
}

allprojects {
    group = 'mc233'
    version = '3.7.4_A1'
}

// 根项目只是聚合器，不产出 jar
subprojects {
    apply plugin: 'java'

    repositories {
        mavenCentral()
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
        maven { url = 'https://repo.opencollab.dev/maven-snapshots/' }
        maven { url = 'https://repo.opencollab.dev/maven-releases/' }
        maven { url = 'https://oss.sonatype.org/content/groups/public/' }
        maven { url = 'https://jitpack.io' }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release.set(21)
    }
}
